#! /bin/sh
#
# Script by Jakub Jelinek
# Modified by Ian Zimmerman <itz@rahul.net> to reflect names from
# kernel device list
# $Id: create_vcs,v 1.2 2002/05/28 19:13:52 nico Exp $

if test -e /dev/vcs0 || test -e /dev/vcs
then
	exit
fi

I=0
while [ $I -lt 25 ] 
do
        mknod /dev/vcs$I c 7 $I
        chmod 622 /dev/vcs$I
        chown root.tty /dev/vcs$I
        mknod /dev/vcsa$I c 7 `expr $I + 128`
        chmod 622 /dev/vcsa$I
        chown root.tty /dev/vcsa$I
        I=`expr $I + 1`
done
ln -s vcs0 /dev/vcs
ln -s vcsa0 /dev/vcsa
