#!/bin/sh
#
# Date: 26th of September 2001
# Description: still missing
# Author: Nico Schottelius (nicos@pcsystems.de), 26th of September 2001
# Copying: GPL 2.0
#

if [ $# -ne 1 ]; then
   echo `basename $0`': dir'
   echo 'Hey, hey guy, what to release ?'
   exit 1
fi

if [ ! -d $1 ]; then
   echo `basename $0`': dir'
   echo 'HEY! DIRECTORY! We need a gpm directory!'
   exit 1
fi

version=`echo $1 | sed 's/\/$//' | sed 's/gpm-//'`
echo -n "Releasing gpm-$version ..."

cd $1

cat configure.in | sed "s/release=.\*/release=$version/" > configure.on
mv configure.on configure.in
autoconf

cat src/headers/gpmCfg.h | sed "s/\(#define GPM_DATE\).*/\1    \"`date`\"/" > src/headers/gpmCfg.i; mv src/headers/gpmCfg.i src/headers/gpmCfg.h

cd ..

tar cfz gpm-$version.tar.gz  $1
tar cfI gpm-$version.tar.bz2 $1

echo done.
