#!/bin/sh
#
# Date: 18th of September 2001
# Description: Test gpm with this script :)
# Author: Nico Schottelius (nicos@pcsystems.de), 3rd of October 2001
# Copying: GPL 2.0
# Version: 0.2
#

PREFIX=test-
POSTFIX=

if [ $# -ne 1 ]; then
   echo `basename $0`': dir'
   echo 'Hey, hey guy, what to test ?'
   exit 1
fi

if [ ! -d $1 ]; then
   echo `basename $0`': dir'
   echo 'HEY! I need a DIRECTORY! Not something else!'
   exit 1
fi

echo rm -rf $PREFIX`basename $1`$POSTFIX -r
rm -rf $PREFIX`basename $1`$POSTFIX -r
echo cp $1 $PREFIX`basename $1`$POSTFIX -r
cp $1 $PREFIX`basename $1`$POSTFIX -r

echo rm -rf mkdir objdir
rm -rf objdir/ && mkdir -p objdir && cd objdir
echo configure
../$PREFIX`basename $1`$POSTFIX/configure --prefix=/usr/sys
echo make
make
